<a href="https://colab.research.google.com/github/souravlouha/All_ML_session/blob/main/Array_Create_in_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

create 0 dimentional array


In [ ]:
arrd0 = np.array(42)

In [ ]:
print(arrd0) #ai khane akti matro single element store kora holo , ar akti 0 dimentional array create kora holo
print(arrd0.ndim)#object that returns the number of dimensions (axes) of the array

42
0


creat 1 dimentional array

In [ ]:
arrd1 = np.array([1, 2, 3, 4, 5])

print(arrd1)
print(arrd1.ndim)#object that returns the number of dimensions (axes) of the array

[1 2 3 4 5]
1


creat 2 dimentional array

In [ ]:
arrd2 =np.array([[1,2,3],[2,3,4]])

print(arrd2)
print(arrd2.ndim)

[[1 2 3]
 [2 3 4]]
2


creat 3 dimentional array

In [ ]:
arrd3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

print(arrd3)
print(arrd3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [ ]:
# ndim show korbe , array ra dimention koto .
# shape show korbe koyta element store ache tate .
# ndmin is a parameter in NumPy used when creating arrays. It specifies the minimum number of dimensions that the resulting array should have.
      # For example, ndmin =3 koreo 3 dimentional array create kora jete pari .

In [ ]:
d7 = np.array([1,2,3],ndmin=7) # ndmin ar help niye 7 dimention ar akta array create kora holo
d7

array([[[[[[[1, 2, 3]]]]]]])

In [ ]:
d7.ndim

7

In [ ]:
d7.shape

(1, 1, 1, 1, 1, 1, 3)

Indexing of array in Numpy

In [ ]:
arrd1

array([1, 2, 3, 4, 5])

In [ ]:
arrd1[1] # array 1 ar , bhetore thaka element gulo ke indexing kora hochhe

2

In [ ]:
arrd1[1:4]

array([2, 3, 4])

In [ ]:
# array 2
arrd2

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
arrd2[1,1:3] # array 2 ar ; 1 represent korche row number ta ke , ar pore 1:3 represents korche slicing,


array([3, 4])

In [ ]:
arrd2[0,0:3]

array([1, 2, 3])

In [ ]:
# 2 array te value change kora hobe

arrd2[1,2]=1000
arrd2

array([[   1,    2,    3],
       [   2,    3, 1000]])

In [ ]:
D3 =np.array([[[1,2,3],[2,3,4]],[[11,25,34],[71,26,43]],[[753,841,964],[957,864,426]]])
D3

array([[[  1,   2,   3],
        [  2,   3,   4]],

       [[ 11,  25,  34],
        [ 71,  26,  43]],

       [[753, 841, 964],
        [957, 864, 426]]])

In [ ]:
D3.shape # it means 3 te total 2d array ache ar tate 2 to kore row ar tate 3 te kore element ache

(3, 2, 3)

In [ ]:
D3.ndim # dimention

3

In [ ]:
# value change kora hobe
D3[1,1,1]=1000
D3

array([[[   1,    2,    3],
        [   2,    3,    4]],

       [[  11,   25,   34],
        [  71, 1000,   43]],

       [[ 753,  841,  964],
        [ 957,  864,  426]]])

In [ ]:
# kono array ar, modhhe thaka element gulo, extract kore print kora jete pare , 2 bhabe/ methods kora jete pare ; first holo loop ar help niye , second function use kore .

In [ ]:
for i in D3:  # ai gulo loop diye kora holo
  for j in i:
    print(j)

[1 2 3]
[2 3 4]
[11 25 34]
[  71 1000   43]
[753 841 964]
[957 864 426]


In [ ]:
for i in D3: # ai gulo loop diye kora holo
  for j in i:
    for k in j:
      print(k)

1
2
3
2
3
4
11
25
34
71
1000
43
753
841
964
957
864
426


In [ ]:
# Numpy ar fuinctions diye perform kora hobe

for i,j in np.ndenumerate(D3):
  print(i,j)   # ai function ti , indexing somet elements gulo ke print kore

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 2
(0, 1, 1) 3
(0, 1, 2) 4
(1, 0, 0) 11
(1, 0, 1) 25
(1, 0, 2) 34
(1, 1, 0) 71
(1, 1, 1) 1000
(1, 1, 2) 43
(2, 0, 0) 753
(2, 0, 1) 841
(2, 0, 2) 964
(2, 1, 0) 957
(2, 1, 1) 864
(2, 1, 2) 426


In [ ]:
for i in np.nditer(D3): # ata o akta function , element gulo with out indexing kore print kore
 print(i)

1
2
3
2
3
4
11
25
34
71
1000
43
753
841
964
957
864
426


In [ ]:
# np.ndenumerate ->  ai function ti , indexing somet elements gulo ke print kore
# np.nditer -> ata o akta function , element gulo with out indexing kore print kore

In [ ]:
d7

array([[[[[[[1, 2, 3]]]]]]])

In [ ]:
# akhane 7 ti lear ache , karon ati 7 dimentional array
# atar elements gulo ke extract korte hole 7 bar loop chalate hobe , tai amra Functions ar help nibio


In [ ]:
for i,j in np.ndenumerate(d7):
  print(i,j)

(0, 0, 0, 0, 0, 0, 0) 1
(0, 0, 0, 0, 0, 0, 1) 2
(0, 0, 0, 0, 0, 0, 2) 3


In [ ]:
for i in np.nditer(d7):
  print(i)

1
2
3
