<a href="https://colab.research.google.com/github/souravlouha/All_ML_session/blob/main/day01_tmsl_college.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("welcome to colab")
print("numpy basic")

welcome to colab
numpy basic


In [4]:
import numpy as np

# Single Dimensional Array


In [5]:
a = np.array([12,5,7,13,6,9,15,2,1])
print(a)

[12  5  7 13  6  9 15  2  1]


In [6]:
a.ndim #how many dimension of array

1

In [7]:
a.dtype

dtype('int64')

In [8]:
a.shape #how many element and size of array

(9,)

In [9]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype='int32')


In [10]:
a1.dtype

dtype('int32')

In [11]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [12]:
a1.dtype

dtype('int32')

In [13]:
a2 = a1.astype(np.int32)

In [14]:
a2.dtype

dtype('int32')

In [15]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [16]:
a2[-1]

1

In [17]:
a2[len(a2)-1]

1

In [18]:
a2[2:6] #slicing ; common diff 1 thake


array([ 7, 13,  6,  9], dtype=int32)

In [19]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [20]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [21]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [22]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [23]:
a2[0:len(a2):2]

array([12,  7,  6, 15,  1], dtype=int32)

In [24]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [25]:
a2[0:len(a2):-1]

array([], dtype=int32)

In [26]:
a2[-1:-len(a2)-1:-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [27]:
a2[[1,3,6]] #special indexing

array([ 5, 13, 15], dtype=int32)

In [28]:
a2[[3,1,6]]

array([13,  5, 15], dtype=int32)

In [29]:
a3 = np.random.randint(1,100,10)

In [30]:
a3

array([33, 62, 66, 21, 12, 64, 73, 64, 60, 25])

In [31]:
a3[a3>=50]

array([62, 66, 64, 73, 64, 60])

In [32]:
a3>=50

array([False,  True,  True, False, False,  True,  True,  True,  True,
       False])

In [33]:
a3[[False,  True,  True, False, False,  True,  True,  True,  True,
       False]]

array([62, 66, 64, 73, 64, 60])