<a href="https://colab.research.google.com/github/souravlouha/All_ML_session/blob/main/day01_tmsl_college.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("welcome to colab")
print("numpy basic")

welcome to colab
numpy basic


In [ ]:
import numpy as np

# Single Dimensional Array


In [ ]:
a = np.array([12,5,7,13,6,9,15,2,1])
print(a)

[12  5  7 13  6  9 15  2  1]


In [ ]:
a.ndim #how many dimension of array

1

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a.shape #how many element and size of array

(9,)

In [ ]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype='int32')


In [ ]:
a1.dtype

dtype('int32')

In [ ]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [ ]:
a1.dtype

dtype('int32')

In [ ]:
a2 = a1.astype(np.int32)

In [ ]:
a2.dtype

dtype('int32')

In [ ]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [ ]:
a2[-1]

1

In [ ]:
a2[len(a2)-1]

1

In [ ]:
a2[2:6] #slicing ; common diff 1 thake


array([ 7, 13,  6,  9], dtype=int32)

In [ ]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [ ]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [ ]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [ ]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [ ]:
a2[0:len(a2):2]

array([12,  7,  6, 15,  1], dtype=int32)

In [ ]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [ ]:
a2[0:len(a2):-1]

array([], dtype=int32)

In [ ]:
a2[-1:-len(a2)-1:-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [ ]:
a2[[1,3,6]] #special indexing

array([ 5, 13, 15], dtype=int32)

In [ ]:
a2[[3,1,6]]

array([13,  5, 15], dtype=int32)

In [ ]:
a3 = np.random.randint(1,100,10)

In [ ]:
a3

array([33, 62, 66, 21, 12, 64, 73, 64, 60, 25])

In [ ]:
a3[a3>=50]

array([62, 66, 64, 73, 64, 60])

In [ ]:
a3>=50

array([False,  True,  True, False, False,  True,  True,  True,  True,
       False])

In [ ]:
a3[[False,  True,  True, False, False,  True,  True,  True,  True,
       False]]

array([62, 66, 64, 73, 64, 60])

In [ ]:
a3[(a3>=40) & (a3<=60)]

array([60])

In [ ]:
a3[(a3<=40) | (a3>=60)]

array([33, 62, 66, 21, 12, 64, 73, 64, 60, 25])

In [ ]:
a3[~((a3>=40) & (a3<=60))] # ~ this is the not opparatar in numpy

array([33, 62, 66, 21, 12, 64, 73, 64, 25])

In [ ]:
a4 = np.random.randint(1,100,10)
a5 = np.random.randint(1,100,10)

In [ ]:
a4

array([99, 58, 43, 84, 94, 90, 17, 21, 49,  5])

In [ ]:
a5

array([78, 35, 49, 10, 91, 30, 81, 20, 62,  5])

In [ ]:
a6= a4+a5

In [ ]:
a6

array([177,  93,  92,  94, 185, 120,  98,  41, 111,  10])

In [ ]:
np.sin(a6) #universal function :=ufunc

array([ 0.87758979, -0.94828214, -0.77946607, -0.24525199,  0.34662118,
        0.58061118, -0.57338187, -0.15862267, -0.86455145, -0.54402111])

In [ ]:
np.log10(a6)

array([2.24797327, 1.96848295, 1.96378783, 1.97312785, 2.26717173,
       2.07918125, 1.99122608, 1.61278386, 2.04532298, 1.        ])

In [ ]:
a6.sum()

1021

In [ ]:
a6 +=10 # Broadcasting

In [ ]:
a6

array([197, 113, 112, 114, 205, 140, 118,  61, 131,  30])

#Tow D arrays


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2d array

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
b.ndim

2

In [ ]:
b.shape

(3, 3)

In [ ]:
a7 = np.arange(1,13)

In [ ]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
b1= a7.reshape(3,4)

In [ ]:
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2= a7.reshape(3,-1)

In [ ]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b3= a7.reshape(-1,4)

In [ ]:
b3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a7.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [ ]:
a7.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [ ]:
b4 = np.random.randint(1,100,(7,8)) # aikhane 7,8 ar akti matrix creat korlam

In [ ]:
b4

array([[23, 90,  3, 66, 29, 59,  2, 25],
       [21, 71, 73, 84, 27, 26, 48, 74],
       [60, 81, 20, 43, 73, 98, 72, 20],
       [86,  5, 77, 85, 19,  2, 58, 32],
       [62, 92, 13, 60, 88, 60, 91, 22],
       [ 5, 20, 41, 49, 66, 29, 76, 88],
       [90, 84, 85, 39, 63, 66, 76, 99]])

In [ ]:
b4[2] # ata row ar number dile , sei row tai show kore ;; indexing

array([60, 81, 20, 43, 73, 98, 72, 20])

In [ ]:
b4[2:3] # ata slicing

array([[60, 81, 20, 43, 73, 98, 72, 20]])

In [ ]:
b4[2][3] # ata kono row ar kono akti nidisto coloum ke ber kora jay

43

In [ ]:
b4[2,3] # ata kono row ar kono akti nidisto coloum ke ber kora jay ;; atao akta process

43

In [ ]:
b4[1::2]

array([[21, 71, 73, 84, 27, 26, 48, 74],
       [86,  5, 77, 85, 19,  2, 58, 32],
       [ 5, 20, 41, 49, 66, 29, 76, 88]])

In [ ]:
b4[:,3] # coloum ber korar tecniq , kono coloum ber korte gele ai bhabe likhte hobe

array([66, 84, 43, 85, 60, 49, 39])

In [ ]:
b4[1:4:2,1:6:2]

array([[71, 84, 26],
       [ 5, 85,  2]])

In [ ]:
b4[[1,3,6],1:6:2] #complex slicing

array([[71, 84, 26],
       [ 5, 85,  2],
       [84, 39, 66]])

In [ ]:
b4[[1,3,6],[1,6,2]]

array([71, 58, 85])

In [ ]:
b4[[1,3,6]][:,[1,6,2]]

array([[71, 48, 73],
       [ 5, 58, 77],
       [84, 76, 85]])

In [ ]:
b4[:,[1,3,6]][[1,6,2]]

array([[71, 84, 48],
       [84, 39, 76],
       [81, 43, 72]])

In [ ]:
b5= np.random.randint(1,100,(3,4))
b6= np.random.randint(1,100,(3,4))

In [ ]:
b5

array([[22, 59, 95, 61],
       [61,  9, 64, 62],
       [79, 60, 25, 83]])

In [ ]:
b6

array([[38, 13, 47, 10],
       [60, 24, 28,  6],
       [21, 95, 45, 65]])

In [ ]:
b5*b6

array([[ 836,  767, 4465,  610],
       [3660,  216, 1792,  372],
       [1659, 5700, 1125, 5395]])

In [ ]:
b7= np.random.randint(1,100,(3,4))
b8= np.random.randint(1,100,(4,3))

In [ ]:
b7.dot(b8)

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])

In [ ]:
np.dot(b7,b8)

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])

In [ ]:
b7@b8

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])

In [ ]:
b9= np.random.randint(1,10,(5,4))
b10= np.random.randint(1,10,(3,4))

In [ ]:
b9

array([[9, 2, 3, 8],
       [2, 2, 2, 1],
       [9, 2, 8, 2],
       [8, 2, 9, 3],
       [2, 6, 4, 2]])

In [ ]:
b10

array([[4, 9, 4, 2],
       [4, 1, 8, 9],
       [7, 2, 7, 2]])

In [ ]:
np.vstack([b9,b10])

array([[9, 2, 3, 8],
       [2, 2, 2, 1],
       [9, 2, 8, 2],
       [8, 2, 9, 3],
       [2, 6, 4, 2],
       [4, 9, 4, 2],
       [4, 1, 8, 9],
       [7, 2, 7, 2]])

#system of linear equation


In [39]:
A = np.array([[3,2,-1],[2,-2,4],[-1,0.5,-1]])
B = np.array([1,-2,0])

In [40]:
x =np.linalg.solve(A,B)

In [42]:
x

array([ 1., -2., -2.])

In [41]:
np.allclose(A@x,B)

True

# vectorization

In [43]:
a = np.random.randint(1,10,(7,8))


In [45]:
def tactorial(n):
  return 1 if n==0 else n*tactorial(n-1)

In [47]:
tactorial(5)

120

In [48]:
b = np.zeros_like(a)

In [49]:
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    b[i,j] = tactorial(a[i,j])

In [51]:
b

array([[     2,    720, 362880,     24,    120,      1,     24,      6],
       [ 40320,      2,    120,    720,    120,      6,  40320,    720],
       [    24,    120,    720,      1,   5040,     24,    120,    720],
       [   720,     24,  40320,    720, 362880,    720,      1,    120],
       [     1,  40320,      6,      6,     24,      6,      1,    120],
       [    24,    120,      6, 362880,   5040,     24,      6,      6],
       [    24,   5040,   5040,      1, 362880,      1,  40320,      6]])

In [53]:
vec_fact = np.vectorize(tactorial)

In [54]:
vec_fact(a)

array([[     2,    720, 362880,     24,    120,      1,     24,      6],
       [ 40320,      2,    120,    720,    120,      6,  40320,    720],
       [    24,    120,    720,      1,   5040,     24,    120,    720],
       [   720,     24,  40320,    720, 362880,    720,      1,    120],
       [     1,  40320,      6,      6,     24,      6,      1,    120],
       [    24,    120,      6, 362880,   5040,     24,      6,      6],
       [    24,   5040,   5040,      1, 362880,      1,  40320,      6]])

In [55]:
@np.vectorize#factorial = np.vectorize(factorial)
def factorial(n):
  return 1 if n==0 else n*factorial(n-1)

In [56]:
factorial(a)

array([[     2,    720, 362880,     24,    120,      1,     24,      6],
       [ 40320,      2,    120,    720,    120,      6,  40320,    720],
       [    24,    120,    720,      1,   5040,     24,    120,    720],
       [   720,     24,  40320,    720, 362880,    720,      1,    120],
       [     1,  40320,      6,      6,     24,      6,      1,    120],
       [    24,    120,      6, 362880,   5040,     24,      6,      6],
       [    24,   5040,   5040,      1, 362880,      1,  40320,      6]])