<a href="https://colab.research.google.com/github/souravlouha/All_ML_session/blob/main/day01_tmsl_college.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("welcome to colab")
print("numpy basic")

welcome to colab
numpy basic


In [4]:
import numpy as np

# Single Dimensional Array


In [5]:
a = np.array([12,5,7,13,6,9,15,2,1])
print(a)

[12  5  7 13  6  9 15  2  1]


In [6]:
a.ndim #how many dimension of array

1

In [7]:
a.dtype

dtype('int64')

In [8]:
a.shape #how many element and size of array

(9,)

In [9]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype='int32')


In [10]:
a1.dtype

dtype('int32')

In [11]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [12]:
a1.dtype

dtype('int32')

In [13]:
a2 = a1.astype(np.int32)

In [14]:
a2.dtype

dtype('int32')

In [15]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [16]:
a2[-1]

1

In [17]:
a2[len(a2)-1]

1

In [18]:
a2[2:6] #slicing ; common diff 1 thake


array([ 7, 13,  6,  9], dtype=int32)

In [19]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [20]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [21]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [22]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [23]:
a2[0:len(a2):2]

array([12,  7,  6, 15,  1], dtype=int32)

In [24]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [25]:
a2[0:len(a2):-1]

array([], dtype=int32)

In [26]:
a2[-1:-len(a2)-1:-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [27]:
a2[[1,3,6]] #special indexing

array([ 5, 13, 15], dtype=int32)

In [28]:
a2[[3,1,6]]

array([13,  5, 15], dtype=int32)

In [29]:
a3 = np.random.randint(1,100,10)

In [30]:
a3

array([33, 62, 66, 21, 12, 64, 73, 64, 60, 25])

In [31]:
a3[a3>=50]

array([62, 66, 64, 73, 64, 60])

In [32]:
a3>=50

array([False,  True,  True, False, False,  True,  True,  True,  True,
       False])

In [33]:
a3[[False,  True,  True, False, False,  True,  True,  True,  True,
       False]]

array([62, 66, 64, 73, 64, 60])

In [36]:
a3[(a3>=40) & (a3<=60)]

array([60])

In [37]:
a3[(a3<=40) | (a3>=60)]

array([33, 62, 66, 21, 12, 64, 73, 64, 60, 25])

In [39]:
a3[~((a3>=40) & (a3<=60))] # ~ this is the not opparatar in numpy

array([33, 62, 66, 21, 12, 64, 73, 64, 25])

In [40]:
a4 = np.random.randint(1,100,10)
a5 = np.random.randint(1,100,10)

In [41]:
a4

array([99, 58, 43, 84, 94, 90, 17, 21, 49,  5])

In [42]:
a5

array([78, 35, 49, 10, 91, 30, 81, 20, 62,  5])

In [43]:
a6= a4+a5

In [44]:
a6

array([177,  93,  92,  94, 185, 120,  98,  41, 111,  10])

In [45]:
np.sin(a6) #universal function :=ufunc

array([ 0.87758979, -0.94828214, -0.77946607, -0.24525199,  0.34662118,
        0.58061118, -0.57338187, -0.15862267, -0.86455145, -0.54402111])

In [46]:
np.log10(a6)

array([2.24797327, 1.96848295, 1.96378783, 1.97312785, 2.26717173,
       2.07918125, 1.99122608, 1.61278386, 2.04532298, 1.        ])

In [47]:
a6.sum()

1021

In [49]:
a6 +=10 # Broadcasting

In [50]:
a6

array([197, 113, 112, 114, 205, 140, 118,  61, 131,  30])

#Tow D arrays


In [52]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2d array

In [54]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
b.ndim

2

In [56]:
b.shape

(3, 3)

In [57]:
a7 = np.arange(1,13)

In [58]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [59]:
b1= a7.reshape(3,4)

In [60]:
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
b2= a7.reshape(3,-1)

In [62]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b3= a7.reshape(-1,4)

In [64]:
b3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
a7.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [66]:
a7.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [68]:
b4 = np.random.randint(1,100,(7,8)) # aikhane 7,8 ar akti matrix creat korlam

In [69]:
b4

array([[23, 90,  3, 66, 29, 59,  2, 25],
       [21, 71, 73, 84, 27, 26, 48, 74],
       [60, 81, 20, 43, 73, 98, 72, 20],
       [86,  5, 77, 85, 19,  2, 58, 32],
       [62, 92, 13, 60, 88, 60, 91, 22],
       [ 5, 20, 41, 49, 66, 29, 76, 88],
       [90, 84, 85, 39, 63, 66, 76, 99]])

In [70]:
b4[2] # ata row ar number dile , sei row tai show kore ;; indexing

array([60, 81, 20, 43, 73, 98, 72, 20])

In [73]:
b4[2:3] # ata slicing

array([[60, 81, 20, 43, 73, 98, 72, 20]])

In [74]:
b4[2][3] # ata kono row ar kono akti nidisto coloum ke ber kora jay

43

In [75]:
b4[2,3] # ata kono row ar kono akti nidisto coloum ke ber kora jay ;; atao akta process

43

In [79]:
b4[1::2]

array([[21, 71, 73, 84, 27, 26, 48, 74],
       [86,  5, 77, 85, 19,  2, 58, 32],
       [ 5, 20, 41, 49, 66, 29, 76, 88]])

In [82]:
b4[:,3] # coloum ber korar tecniq , kono coloum ber korte gele ai bhabe likhte hobe

array([66, 84, 43, 85, 60, 49, 39])

In [83]:
b4[1:4:2,1:6:2]

array([[71, 84, 26],
       [ 5, 85,  2]])

In [84]:
b4[[1,3,6],1:6:2] #complex slicing

array([[71, 84, 26],
       [ 5, 85,  2],
       [84, 39, 66]])

In [89]:
b4[[1,3,6],[1,6,2]]

array([71, 58, 85])

In [91]:
b4[[1,3,6]][:,[1,6,2]]

array([[71, 48, 73],
       [ 5, 58, 77],
       [84, 76, 85]])

In [92]:
b4[:,[1,3,6]][[1,6,2]]

array([[71, 84, 48],
       [84, 39, 76],
       [81, 43, 72]])

In [94]:
b5= np.random.randint(1,100,(3,4))
b6= np.random.randint(1,100,(3,4))

In [95]:
b5

array([[22, 59, 95, 61],
       [61,  9, 64, 62],
       [79, 60, 25, 83]])

In [96]:
b6

array([[38, 13, 47, 10],
       [60, 24, 28,  6],
       [21, 95, 45, 65]])

In [97]:
b5*b6

array([[ 836,  767, 4465,  610],
       [3660,  216, 1792,  372],
       [1659, 5700, 1125, 5395]])

In [98]:
b7= np.random.randint(1,100,(3,4))
b8= np.random.randint(1,100,(4,3))

In [100]:
b7.dot(b8)

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])

In [101]:
np.dot(b7,b8)

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])

In [102]:
b7@b8

array([[ 8432, 13202,  7816],
       [10524, 17338,  9726],
       [15598, 20733,  9695]])