<a href="https://colab.research.google.com/github/souravlouha/All_ML_session/blob/main/day01_tmsl_college.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
print("welcome to colab")
print("numpy basic")

welcome to colab
numpy basic


In [58]:
import numpy as np

# Single Dimensional Array


In [59]:
a = np.array([12,5,7,13,6,9,15,2,1])
print(a)

[12  5  7 13  6  9 15  2  1]


In [60]:
a.ndim #how many dimension of array

1

In [61]:
a.dtype

dtype('int64')

In [62]:
a.shape #how many element and size of array

(9,)

In [63]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype='int32')


In [64]:
a1.dtype

dtype('int32')

In [65]:
a1 = np.array([12,5,7,13,6,9,15,2,1],dtype=np.int32)

In [66]:
a1.dtype

dtype('int32')

In [67]:
a2 = a1.astype(np.int32)

In [ ]:
a2.dtype

dtype('int32')

In [68]:
a2

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [69]:
a2[-1]

1

In [70]:
a2[len(a2)-1]

1

In [71]:
a2[2:6] #slicing ; common diff 1 thake


array([ 7, 13,  6,  9], dtype=int32)

In [72]:
a2[2:]

array([ 7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [73]:
a2[:]

array([12,  5,  7, 13,  6,  9, 15,  2,  1], dtype=int32)

In [74]:
a2[1:7:2]

array([ 5, 13,  9], dtype=int32)

In [75]:
a2[::2]

array([12,  7,  6, 15,  1], dtype=int32)

In [76]:
a2[0:len(a2):2]

array([12,  7,  6, 15,  1], dtype=int32)

In [77]:
a2[::-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [78]:
a2[0:len(a2):-1]

array([], dtype=int32)

In [79]:
a2[-1:-len(a2)-1:-1]

array([ 1,  2, 15,  9,  6, 13,  7,  5, 12], dtype=int32)

In [80]:
a2[[1,3,6]] #special indexing

array([ 5, 13, 15], dtype=int32)

In [81]:
a2[[3,1,6]]

array([13,  5, 15], dtype=int32)

In [82]:
a3 = np.random.randint(1,100,10)

In [83]:
a3

array([22, 90, 48, 68, 72,  2, 19, 85,  2, 19])

In [84]:
a3[a3>=50]

array([90, 68, 72, 85])

In [85]:
a3>=50

array([False,  True, False,  True,  True, False, False,  True, False,
       False])

In [86]:
a3[[False,  True,  True, False, False,  True,  True,  True,  True,
       False]]

array([90, 48,  2, 19, 85,  2])

In [87]:
a3[(a3>=40) & (a3<=60)]

array([48])

In [88]:
a3[(a3<=40) | (a3>=60)]

array([22, 90, 68, 72,  2, 19, 85,  2, 19])

In [89]:
a3[~((a3>=40) & (a3<=60))] # ~ this is the not opparatar in numpy

array([22, 90, 68, 72,  2, 19, 85,  2, 19])

In [90]:
a4 = np.random.randint(1,100,10)
a5 = np.random.randint(1,100,10)

In [92]:
a4

array([18, 65, 52, 22,  7, 92, 38,  7, 17, 53])

In [93]:
a5

array([83, 44, 60, 59, 18, 58, 29, 21, 51, 64])

In [94]:
a6= a4+a5

In [95]:
a6

array([101, 109, 112,  81,  25, 150,  67,  28,  68, 117])

In [96]:
np.sin(a6) #universal function :=ufunc

array([ 0.45202579,  0.81674261, -0.8899956 , -0.62988799, -0.13235175,
       -0.71487643, -0.85551998,  0.27090579, -0.89792768, -0.68969794])

In [97]:
np.log10(a6)

array([2.00432137, 2.0374265 , 2.04921802, 1.90848502, 1.39794001,
       2.17609126, 1.8260748 , 1.44715803, 1.83250891, 2.06818586])

In [98]:
a6.sum()

858

In [99]:
a6 +=10 # Broadcasting

In [100]:
a6

array([111, 119, 122,  91,  35, 160,  77,  38,  78, 127])

#Tow D arrays


In [101]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]]) # 2d array

In [102]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
b.ndim

2

In [104]:
b.shape

(3, 3)

In [105]:
a7 = np.arange(1,13)

In [106]:
a7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [107]:
b1= a7.reshape(3,4)

In [108]:
b1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [109]:
b2= a7.reshape(3,-1)

In [110]:
b2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [111]:
b3= a7.reshape(-1,4)

In [112]:
b3

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
a7.reshape(-1,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [114]:
a7.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [115]:
b4 = np.random.randint(1,100,(7,8)) # aikhane 7,8 ar akti matrix creat korlam

In [116]:
b4

array([[35, 21, 34,  6, 13, 49, 88, 36],
       [26, 46, 58, 73, 89, 88, 60, 59],
       [21, 17, 69, 35,  6, 97, 25, 86],
       [48, 85, 54, 59, 17, 45, 25, 25],
       [81, 46, 38, 20, 58, 48, 54, 27],
       [58, 35, 71, 70, 39, 69, 22, 99],
       [32, 67, 94, 10, 52, 32, 83, 86]])

In [117]:
b4[2] # ata row ar number dile , sei row tai show kore ;; indexing

array([21, 17, 69, 35,  6, 97, 25, 86])

In [118]:
b4[2:3] # ata slicing

array([[21, 17, 69, 35,  6, 97, 25, 86]])

In [119]:
b4[2][3] # ata kono row ar kono akti nidisto coloum ke ber kora jay

35

In [120]:
b4[2,3] # ata kono row ar kono akti nidisto coloum ke ber kora jay ;; atao akta process

35

In [121]:
b4[1::2]

array([[26, 46, 58, 73, 89, 88, 60, 59],
       [48, 85, 54, 59, 17, 45, 25, 25],
       [58, 35, 71, 70, 39, 69, 22, 99]])

In [122]:
b4[:,3] # coloum ber korar tecniq , kono coloum ber korte gele ai bhabe likhte hobe

array([ 6, 73, 35, 59, 20, 70, 10])

In [123]:
b4[1:4:2,1:6:2]

array([[46, 73, 88],
       [85, 59, 45]])

In [124]:
b4[[1,3,6],1:6:2] #complex slicing

array([[46, 73, 88],
       [85, 59, 45],
       [67, 10, 32]])

In [125]:
b4[[1,3,6],[1,6,2]]

array([46, 25, 94])

In [126]:
b4[[1,3,6]][:,[1,6,2]]

array([[46, 60, 58],
       [85, 25, 54],
       [67, 83, 94]])

In [127]:
b4[:,[1,3,6]][[1,6,2]]

array([[46, 73, 60],
       [67, 10, 83],
       [17, 35, 25]])

In [128]:
b5= np.random.randint(1,100,(3,4))
b6= np.random.randint(1,100,(3,4))

In [129]:
b5

array([[87,  3, 36, 99],
       [91, 17, 86,  7],
       [34, 47, 81, 82]])

In [130]:
b6

array([[13, 42, 50, 75],
       [34, 13, 99, 96],
       [97, 71, 33, 28]])

In [131]:
b5*b6

array([[1131,  126, 1800, 7425],
       [3094,  221, 8514,  672],
       [3298, 3337, 2673, 2296]])

In [132]:
b7= np.random.randint(1,100,(3,4))
b8= np.random.randint(1,100,(4,3))

In [133]:
b7.dot(b8)

array([[ 5387,  3500,  3607],
       [13902, 12840,  7518],
       [13069, 13501,  8654]])

In [134]:
np.dot(b7,b8)

array([[ 5387,  3500,  3607],
       [13902, 12840,  7518],
       [13069, 13501,  8654]])

In [135]:
b7@b8

array([[ 5387,  3500,  3607],
       [13902, 12840,  7518],
       [13069, 13501,  8654]])

In [136]:
b9= np.random.randint(1,10,(5,4))
b10= np.random.randint(1,10,(3,4))

In [137]:
b9

array([[5, 5, 5, 3],
       [7, 3, 7, 7],
       [4, 1, 4, 7],
       [8, 4, 9, 5],
       [4, 9, 4, 9]])

In [138]:
b10

array([[8, 5, 8, 1],
       [3, 9, 6, 7],
       [8, 7, 9, 9]])

In [139]:
np.vstack([b9,b10])

array([[5, 5, 5, 3],
       [7, 3, 7, 7],
       [4, 1, 4, 7],
       [8, 4, 9, 5],
       [4, 9, 4, 9],
       [8, 5, 8, 1],
       [3, 9, 6, 7],
       [8, 7, 9, 9]])

#system of linear equation


In [140]:
A = np.array([[3,2,-1],[2,-2,4],[-1,0.5,-1]])
B = np.array([1,-2,0])

In [141]:
x =np.linalg.solve(A,B)

In [142]:
x

array([ 1., -2., -2.])

In [143]:
np.allclose(A@x,B)

True

# vectorization

In [144]:
a = np.random.randint(1,10,(7,8))


In [145]:
def tactorial(n):
  return 1 if n==0 else n*tactorial(n-1)

In [147]:
tactorial(5)

120

In [148]:
b = np.zeros_like(a)

In [149]:
b

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [150]:
for i in range(a.shape[0]):
  for j in range(a.shape[1]):
    b[i,j] = tactorial(a[i,j])

In [151]:
b

array([[   720,      1,      6,     24,     24, 362880,     24, 362880],
       [  5040,     24,    120,      6,   5040,    120,      2,   5040],
       [  5040,  40320,    720,      1, 362880,  40320,      1,      1],
       [     2,  40320,      6,    120,     24,   5040,      6,      2],
       [ 40320, 362880,  40320,  40320, 362880,    120,     24,      2],
       [     6,    120,   5040,     24,    720,  40320,      6,      2],
       [  5040,    120,  40320,   5040,      6,      2,      1,    120]])

In [152]:
vec_fact = np.vectorize(tactorial)

In [153]:
vec_fact(a)

array([[   720,      1,      6,     24,     24, 362880,     24, 362880],
       [  5040,     24,    120,      6,   5040,    120,      2,   5040],
       [  5040,  40320,    720,      1, 362880,  40320,      1,      1],
       [     2,  40320,      6,    120,     24,   5040,      6,      2],
       [ 40320, 362880,  40320,  40320, 362880,    120,     24,      2],
       [     6,    120,   5040,     24,    720,  40320,      6,      2],
       [  5040,    120,  40320,   5040,      6,      2,      1,    120]])

In [154]:
@np.vectorize#factorial = np.vectorize(factorial)
def factorial(n):
  return 1 if n==0 else n*factorial(n-1)

In [156]:
factorial(a)

array([[   720,      1,      6,     24,     24, 362880,     24, 362880],
       [  5040,     24,    120,      6,   5040,    120,      2,   5040],
       [  5040,  40320,    720,      1, 362880,  40320,      1,      1],
       [     2,  40320,      6,    120,     24,   5040,      6,      2],
       [ 40320, 362880,  40320,  40320, 362880,    120,     24,      2],
       [     6,    120,   5040,     24,    720,  40320,      6,      2],
       [  5040,    120,  40320,   5040,      6,      2,      1,    120]])